### PR TITLE
Fix/linux amd shader compilation error

### LINKED ISSUE #38: Path tracing broken on Linux
## Description

The path tracing fragment shader does not compile on Linux.
There are multiple locations where sampler arrays are indexed using integer variables.
Compilation fails with this error:
```
0000008 | 2022-04-07, 13:46:57.500381 [warning] - GLShader::compile(Fragment): 0:295(22): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later
```

Here's the complete [logfile.log](https://github.com/allen-cell-animated/agave/files/8445489/logfile.log).

## Reproduction

Start `agave`.

## Environment

OS: Ubuntu 20.04
OpenGL renderer string: AMD RENOIR (LLVM 13.0.0, DRM 3.41, 5.13.0-10039-tuxedo)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.1 - kisak-mesa PPA

### PR DESCRIPTION
**Pull request by toloudis**
Fix errors with compiling shaders at runtime on linux with AMD drivers.
The bug fix is changing the shader version directives from v330 to v400 in the shader source code.

Also because of the nature of this fix, I am removing all occurrences of "v33" in file names and class names.  Lots of files get moved.  A few unused source files are deleted.

Fixes #38 and an issue mentioned in #15

### CODE REVIEW

File: renderlib/glsl/GLBasicVolumeShader.cpp [hunk 1]
```diff
@@ -17,7 +17,7 @@ GLBasicVolumeShader::GLBasicVolumeShader()
 {
   vshader = new GLShader(GL_VERTEX_SHADER);
   vshader->compileSourceCode(R"(
-#version 330 core
+#version 400 core
```
Comment (toloudis) [inline renderlib/glsl/GLBasicVolumeShader.cpp:20]: the changes in this directory of this type constitute the actual bug fix.  All other changes are simple renaming/moving files.

**Review by griffinfujioka — APPROVED** [review]

**Review by kmitcham — APPROVED** [review]
